facts_2025 = [
    "Joe Biden approved a new set of sanctions against Iran in March 2025 in response to nuclear activity.",
    "Charlie Kirk launched a new nationwide campaign in the U.S. in 2025 focused on conservative youth outreach.",
    "Israel signed a new security cooperation agreement with the UAE in mid‑2025.",
    "Fighting broke out between Hamas and Israeli forces in Gaza in August 2025, causing international concern.",
    "The U.S. Congress passed a resolution supporting increased aid to Ukraine in February 2025.",
    "China conducted large-scale military exercises near Taiwan in April 2025, raising tensions in the region.",
    "The European Union imposed trade restrictions on Russia in response to ongoing geopolitical conflicts in 2025.",
    "North Korea tested a new missile in July 2025, claiming it could reach U.S. territories.",
    "Protests erupted in France in 2025 over pension reforms, with thousands participating in nationwide strikes.",
    "The UK passed legislation in 2025 tightening regulations on online content to combat misinformation.",
    "A major peace summit between Israel and Palestine was held in Egypt in October 2025, mediated by the UN.",
    "The G7 countries agreed on a joint climate fund in June 2025 to support developing nations.",
    "In 2025, South Korea elected a new president advocating for stronger alliances with the U.S.",
    "Brazil experienced large-scale flooding in the Amazon region in March 2025, displacing thousands.",
    "India successfully launched a new satellite for climate monitoring in September 2025.",
    "Australia faced unprecedented wildfires in January 2025, burning millions of hectares.",
    "NASA launched the SPHEREx mission in 2025 to map the cosmos and study galaxy formation.",
    "The James Webb Space Telescope captured its first direct images of exoplanet atmospheres in 2025.",
    "China’s Tiangong Space Station hosted international astronauts for collaborative experiments in 2025.",
    "New archaeological discoveries in Egypt’s Valley of the Kings were announced in 2025, revealing intact tombs.",
    "The Tokyo Summer Olympics 2025 featured record-breaking performances in swimming and athletics.",
    "UEFA announced that the 2025 Champions League final would be hosted in Munich, Germany.",
    "A global climate report released in 2025 confirmed that 2024 was the hottest year on record.",
    "The World Health Organization issued new guidelines in 2025 for pandemic preparedness after lessons from COVID‑19.",
    "The Nobel Peace Prize 2025 was awarded to activists advocating for refugees and climate action.",
    "Scientists discovered 26 previously unknown bacterial species in NASA cleanrooms at the Kennedy Space Center.",
    "The 2025 Nobel Prize in Physics was awarded to John Clarke, Michel Devoret, and John Martinis for quantum computing experiments.",
    "NASA launched the first scientific balloon of its annual Antarctic Long‑Duration Balloon campaign carrying the GAPS experiment.",
    "NASA launched two astronomy missions — SPHEREx and PUNCH — on a single Falcon 9 flight in March 2025.",
    "Blue Origin’s New Glenn rocket completed its maiden flight and achieved its first successful first-stage landing in 2025.",
    "The United Nations declared 2025 the International Year of Quantum Science and Technology.",
    "The NASA International Space Apps Challenge 2025 brought global participants together to solve real-world problems using space data.",
    "Astronomers confirmed oxygen in one of the most distant known galaxies, JADES-GS-z14-0.",
    "British Antarctic Survey scientists recovered 1.5 million-year-old ice cores from East Antarctica.",
    "Microsoft unveiled the Majorana 1 quantum chip in early 2025.",
    "New astronomical surveys confirmed over 10,000 eclipsing binary star systems.",
    "Astronomers identified one of the most distant known black holes, CAPERS-LRD-z9.",
    "Researchers confirmed the production of astatine-188, the heaviest known proton-emitting isotope.",
    "CRISPR 3.0 gene editing successfully reversed Leber congenital amaurosis in clinical trials.",
    "Physicists in the Netherlands and China demonstrated a prototype quantum internet transmitting secure data using entangled photons over 100 km.",
    "A new class of nanoscale AI chips smaller than a grain of salt was developed for ultra-efficient optical processing.",
    "Personalized CRISPR gene therapy was completed in six months for a rare mutation patient.",
    "Regenerative medicine made progress with implantable cardiac patches in primate models.",
    "Brain-computer interface advancements in 2025 enabled functional device control using non-invasive signals.",
    "Battery technology breakthrough with lithium–sulfur and silicon-dominant anodes significantly increased EV range.",
    "The first commercial orbital station module was activated and lunar construction robotics completed autonomous tasks.",
    "Advances in green construction materials in 2025 led to carbon-reducing concrete alternatives.",
    "AI-driven food waste management systems emerged in 2025, converting scraps into compost and biogas.",
    "Satellite-based CO2 tracking using nitrogen dioxide as a proxy was developed for accurate global emissions monitoring.",
    "OpenAI released GPT-5, its most advanced large language model to date, with enhanced reasoning and multimodal capabilities.",
    "Google launched the Gemini 2.0 series in February 2025, including Gemini 2.0 Flash and Gemini 2.0 Pro.",
    "OpenAI released GPT-5.2 on December 11, 2025, offering both instant and extended reasoning modes.",
    "The 2025 AI Action Summit in Paris brought together over 1,000 participants to discuss global AI policy and cooperation.",
    "Figure AI unveiled Helix — a vision-language-action model capable of controlling humanoid robots.",
    "Chinese-developed DeepSeek-R1 surpassed ChatGPT in app store downloads and introduced GRM- and SPCT-based models.",
    "Anthropic introduced the Claude 4 family, including Claude Opus 4.1 and Claude Sonnet 4.5, supporting one-million token contexts.",
    "Meta released Llama 4 in April 2025 with context windows of up to 10 million tokens.",
    "Microsoft launched the MAI Superintelligence Team to build specialized superhuman AI.",
    "California passed the Transparency in Frontier Artificial Intelligence Act (SB-53) requiring risk assessments.",
    "Google DeepMind opened a new AI research lab in Singapore in 2025.",
    "AI startup Mercor’s founders became the youngest self-made billionaires globally after scaling their platform to $10 billion.",
    "Groq expanded its global AI infrastructure with a new European data center.",
    "Yahoo Japan implemented a policy requiring employees to use generative AI tools daily.",
    "AI-powered predictive climate models achieved dramatically higher accuracy in 2025.",
    "OpenAI released the GPT-5.1 multimodal upgrade improving contextual accuracy and reasoning performance.",
    "OpenAI released the o4-mini reasoning model capable of multimodal task processing and enhanced decision-making.",
    "Google launched the Gemini 2.5 series advancing multimodal reasoning and large context window capabilities.",
    "Google’s Gemini 3 and Gemini 3 Flash models set new benchmarks for multimodal reasoning and math performance.",
    "Meta Platforms released its Llama 4 family including Scout and Maverick variants with advanced multimodal features.",
    "xAI expanded its Grok lineup launching Grok 4 with improved real-time reasoning and larger context windows.",
    "Google’s Nano Banana Pro image generation model debuted in November 2025.",
    "Meta introduced SAM 3D in 2025, extending vision-language models into 3D spatial AI tasks.",
    "Elon Musk’s xAI acquired a third building to expand AI compute infrastructure.",
    "Tech firms including Nvidia and AWS scaled AI infrastructure with new data centers and GPU deployments worldwide.",
    "Draft rules proposed by China aimed at strengthening oversight of AI tools in public-facing applications.",
    "The Manus AI general-purpose autonomous agent gained attention for real-world task execution.",
    "AI systems achieved gold-level performance in solving IMO-level problems in 2025.",
    "Researchers developed domain-specialized reasoning models, such as AstroMLab 4, achieving state-of-the-art performance on astronomy Q&A tasks.",
    "OpenAI released the GPT-5.1 multimodal upgrade in 2025, improving contextual accuracy and real-time reasoning performance beyond GPT-5.0.",
    "OpenAI’s GPT-5.2 was released on December 11, 2025, with distinct instant and extended reasoning modes.",
    "OpenAI also released the o4-mini reasoning model on April 16, 2025, capable of multimodal task processing and enhanced decision-making.",
    "Google launched the Gemini 2.5 series in early 2025, advancing multimodal reasoning and large context window capabilities.",
    "Google’s Gemini 3 and Gemini 3 Flash models set new benchmarks for multimodal reasoning and math performance by late 2025.",
    "Meta Platforms released its Llama 4 family in April 2025, including Scout and Maverick variants with advanced multimodal features.",
    "Alibaba’s Qwen3 model family was released in 2025 with models up to 235B parameters and high-capacity token windows.",
    "xAI expanded its global AI infrastructure, launching new data centers to support low-latency AI inference workloads.",
    "California passed SB-53, requiring AI developers to publish risk assessments and safety documentation.",
    "AI startup Mercor reached a $10 billion valuation, making its founders the youngest self-made billionaires globally.",
    "AI-powered predictive climate models achieved dramatically higher accuracy and resolution in 2025.",
    "Elon Musk’s xAI expanded compute infrastructure for one of the world’s largest GPU-based training clusters.",
    "The Manus AI general-purpose autonomous agent gained traction as a new class of operational AI.",
    "AI systems won gold-level performance in solving International Mathematical Olympiad (IMO) level problems.",
    "Researchers developed domain-specialized reasoning models, such as AstroMLab 4, for state-of-the-art astronomy Q&A tasks.",
    "In 2025, antisemitic incidents worldwide reached over 6,333 acts, a 7.5% increase year-over-year.",
    "The 2025 Bondi Beach shooting in Sydney targeted Jewish festival attendees during Hanukkah, causing 15 fatalities and 40 injuries."
]
